import "../styles/globals.css";
import type { AppProps } from "next/app";
import { Footer } from "../components/Footer";
import { Navbar } from "../components/Navbar";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Pratham Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="https://unpkg.com/pattern.css" rel="stylesheet" /> */}
      </Head>
      <Navbar></Navbar>

      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
